# Generated by Django 4.1.3 on 2022-11-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço')),
                ('produtoCarrinho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.produto')),
            ],
            options={
                'verbose_name': 'carrinho',
                'verbose_name_plural': 'carrinhos',
                'ordering': ('-pk',),
            },
        ),
    ]
