# Generated by Django 4.1.3 on 2022-11-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='price',
        ),
    ]
