# Generated by Django 4.1.3 on 2022-11-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_carrinho_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade'),
        ),
    ]
